export const posts = [
  {
    id: 1,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "John Doe",
      nickname: "johndoe",
    },
    flames: 10,
    water: 5,
  },
  {
    id: 2,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/women/2.jpg",
      name: "Jane Doe",
      nickname: "janedoe",
    },
    flames: 15,
    water: 8,
  },
  {
    id: 3,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/men/3.jpg",
      name: "Michael Smith",
      nickname: "michaelsmith",
    },
    flames: 20,
    water: 12,
  },
  {
    id: 4,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Emily Johnson",
      nickname: "emilyjohnson",
    },
    flames: 5,
    water: 2,
  },
  {
    id: 5,
    image: `https://picsum.photos/id/5/600/400`,
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Christopher Lee",
      nickname: "christopherlee",
    },
    flames: 30,
    water: 18,
  },
  {
    id: 6,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/women/6.jpg",
      name: "Amanda Jackson",
      nickname: "amandajackson",
    },
    flames: 7,
    water: 3,
  },
  {
    id: 7,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "David Johnson",
      nickname: "davidjohnson",
    },
    flames: 12,
    water: 6,
  },
  {
    id: 8,
    image: "https://picsum.photos/600/400",
    description: "Lorem ipsum dolor sit amet",
    user: {
      photo: "https://randomuser.me/api/portraits/women/8.jpg",
      name: "Jessica Martinez",
      nickname: "jessicamartinez",
    },
    flames: 25,
    water: 15,
  },
];
